routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/forgot', function () {
    return view('auth.passwords.email');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

Route::get('/', 'HomeController@index')->name('home');
//Category//
Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', 'CategoryController@index')->name('view');
});
//Product//
Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', 'ProductController@index')->name('view');
    Route::get('/create', 'ProductController@create')->name('create');
    Route::post('/save', 'ProductController@store')->name('save');
    Route::get('/show/{id}', 'ProductController@show')->name('show');
});
//Order//
Route::group(['prefix' => 'orders', 'as' => 'order.'], function () {
    Route::get('/', 'OrderController@index')->name('view');
    Route::get('/unpaid', 'OrderController@dataUnpaid')->name('unpaid');
    Route::get('/ready', 'OrderController@dataReady')->name('ready');
    Route::get('/complete', 'OrderController@dataComplete')->name('complete');
    Route::get('/show/{id}', 'OrderController@show')->name('show');
    Route::get('/exportorderall/{id}', 'OrderController@exportOrderAll')->name('exportorderall');
    Route::get('/exportdiscountitem/{id}', 'OrderController@exportDiscountItem')->name('exportdiscountitem');
    Route::post('/updatePrint', 'OrderController@updateCountPrint')->name('updatePrint');
    Route::get('/dataOrderAjax', 'OrderController@DataOrderAll')->name('dataAll');
    Route::get('/getbarcode', 'OrderController@barcode')->name('barcode');
    Route::get('/tagsgroup', 'OrderController@barcode')->name('tagsgroup');
    Route::post('/report', 'OrderController@report')->name('report');
});
//User//
Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@index')->name('view');
    Route::get('/create', 'UserController@create')->name('create');
    Route::post('/save', 'UserController@store')->name('save');
    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/update/{id}', 'UserController@update')->name('update');
    Route::post('/disabled', 'UserController@disabled')->name('disabled');
    Route::post('/enabled', 'UserController@enabled')->name('enabled');
    Route::get('/profile/{id}', 'UserController@editProfile')->name('editProfile');
    Route::get('/updateprofile/{id}', 'UserController@updateProfile')->name('updateProfile');
});
//Config//
Route::group(['prefix' => 'configs', 'as' => 'config.'], function () {
    Route::get('/', 'ConfigController@index')->name('view');
    Route::post('/syncdata', 'ConfigController@syncdata')->name('syncdata');
    Route::get('/testdata', 'ConfigController@testdata')->name('testdata');
});
//Shop//
Route::group(['prefix' => 'shops', 'as' => 'shop.'], function () {
    Route::get('/', 'ShopController@index')->name('view');
    Route::get('/edit/{id}', 'ShopController@edit')->name('edit');
});

});

resources/views/flash_msg.blade.php
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


@if (\Session::has('success'))
<div class="alert alert-success">
    <i class="fa fa-check-circle"></i> {!! \Session::get('success') !!}
</div>
@endif

@if (\Session::has('error'))
<div class="alert alert-danger">
    <i class="fa fa-close"></i> {!! \Session::get('error') !!}
</div>
@endif

resources/views/home.blade.php
@extends('layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
            ข้อมูลรวม
            </h1>
            <ol class="breadcrumb">
                <li class="active"><a href="#"><i class="fa fa-dashboard"></i> ข้อมูลรวม</a></li>
            </ol>
        </section>
        <!-- Main content -->
        <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">ข้อมูลการสั่งซื้อล่าสุด</h3>
            </div>
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>รายการสั่งซื้อ</th>
                        <th>สถานะการสั่งซื้อ</th>
                        <th>ผู้สั่งซื้อ</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($orders as $order)
                        <tr>
                            <td><a href="{{ route('order.show',$order->ordersn) }}">{{ $order->ordersn }} </a></td>
                            @php
                                $address = json_decode($order->recipient_address);
                                //
                                $label_color;
                                if($order->order_status == "UNPAID"){
                                    $label_color = 'info';
                                }elseif($order->order_status == 'READY_TO_SHIP'){
                                    $label_color = 'warning';
                                }elseif($order->order_status == 'COMPLETED'){
                                    $label_color = 'success';
                                }elseif($order->order_status == 'IN_CANCEL'){
                                    $label_color = 'warning';
                                }elseif($order->order_status == 'CANCELLED'){
                                    $label_color = 'danger';
                                }elseif($order->order_status == 'TO_RETURN'){
                                    $label_color = 'warning';
                                }
                                //
                            @endphp
                            <td>{{ $order->item->name }}</td>
                            <td><span class="label label-{{ $label_color }}">{{ $order->order_status }}</span></td>
                            <td>
                            <div class="sparkbar" data-color="#00a65a" data-height="20">{{ $address->name }}</div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
            </div>
        </section>
@endsection