routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/forgot', function () {
    return view('auth.passwords.email');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

Route::get('/', 'HomeController@index')->name('home');
//Category//
Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', 'CategoryController@index')->name('view');
});
//Product//
Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', 'ProductController@index')->name('view');
    Route::get('/create', 'ProductController@create')->name('create');
    Route::post('/save', 'ProductController@store')->name('save');
    Route::get('/show/{id}', 'ProductController@show')->name('show');
});
//Order//
Route::group(['prefix' => 'orders', 'as' => 'order.'], function () {
    Route::get('/', 'OrderController@index')->name('view');
    Route::get('/unpaid', 'OrderController@dataUnpaid')->name('unpaid');
    Route::get('/ready', 'OrderController@dataReady')->name('ready');
    Route::get('/complete', 'OrderController@dataComplete')->name('complete');
    Route::get('/show/{id}', 'OrderController@show')->name('show');
    Route::get('/exportorderall/{id}', 'OrderController@exportOrderAll')->name('exportorderall');
    Route::get('/exportdiscountitem/{id}', 'OrderController@exportDiscountItem')->name('exportdiscountitem');
    Route::post('/updatePrint', 'OrderController@updateCountPrint')->name('updatePrint');
    Route::get('/dataOrderAjax', 'OrderController@DataOrderAll')->name('dataAll');
    Route::get('/getbarcode', 'OrderController@barcode')->name('barcode');
    Route::get('/tagsgroup', 'OrderController@barcode')->name('tagsgroup');
    Route::post('/report', 'OrderController@report')->name('report');
});
//User//
Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@index')->name('view');
    Route::get('/create', 'UserController@create')->name('create');
    Route::post('/save', 'UserController@store')->name('save');
    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/update/{id}', 'UserController@update')->name('update');
    Route::post('/disabled', 'UserController@disabled')->name('disabled');
    Route::post('/enabled', 'UserController@enabled')->name('enabled');
    Route::get('/profile/{id}', 'UserController@editProfile')->name('editProfile');
    Route::get('/updateprofile/{id}', 'UserController@updateProfile')->name('updateProfile');
});
//Config//
Route::group(['prefix' => 'configs', 'as' => 'config.'], function () {
    Route::get('/', 'ConfigController@index')->name('view');
    Route::post('/syncdata', 'ConfigController@syncdata')->name('syncdata');
    Route::get('/testdata', 'ConfigController@testdata')->name('testdata');
});
//Shop//
Route::group(['prefix' => 'shops', 'as' => 'shop.'], function () {
    Route::get('/', 'ShopController@index')->name('view');
    Route::get('/edit/{id}', 'ShopController@edit')->name('edit');
});

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $incrementing = false;
    protected $primaryKey = "item_id";
    protected $table = "items";
    protected $fillable = ['item_id',
                        'logistics',
                        'original_price',
                        'package_width',
                        'cmt_count',
                        'weight',
                        'shopid',
                        'currency',
                        'likes',
                        'images',
                        'days_to_ship',
                        'package_length',
                        'stock',
                        'status',
                        'description',
                        'views',
                        'price',
                        'sales',
                        'discount_id',
                        'wholesales',
                        'condition',
                        'package_height',
                        'name',
                        'rating_star',
                        'item_sku',
                        'variations',
                        'size_chart',
                        'has_variation',
                        'attributes',
                        'category_id',
                        ];

    public function Category()
    {
        return $this->belongsTo(Category::Class, 'category_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $products = Product::with('category')
                ->orderBy('category_id', 'DESC')
                ->paginate(20);
        if(!empty($request->get('product'))){
            $products = Product::where('name', 'LIKE', '%'.$request->get('product').'%')->paginate(20);
        }
        if(!empty($request->get('status'))){
            $products = Product::where('status', 'LIKE', '%'.$request->get('status').'%')->paginate(20);
        }
        if(!empty($request->get('category'))){
            $products = Product::where('category_id', 'LIKE', '%'.$request->get('category').'%')->paginate(20);
        }
        $catagories = Category::with('product')->get();
        return view('product.index', compact('products', 'catagories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $catagories = Category::with('product')->get();

        return view('product.create', compact('catagories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'catagory' => 'required',
            'name' => 'required',
            'description' => 'required',
        ],[
            'catagory.required' => 'กรุณาเลือกหมวดหมู่สินค้า',
            'name.required' => 'กรุณาระบุชื่อสินค้า',
            'description.required' => 'กรุณาระบุรายละเอียดสินค้า'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        // dd($data);
        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/product/create.blade.php
@extends('layouts.layout')

@section('content')
    <section class="content-header">
        <h1>
        ข้อมูลผลิตภัณฑ์
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">ข้อมูลผลิตภัณฑ์</li>
            <li class="active"><a href="#"><i class="fa fa-dashboard"></i> เพิ่มสินค้า</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        @include('flash_msg')
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">เพิ่มสินค้า</h3>
            </div>
            <div class="box-body">
                <form class="form-horizontal" action="{{ route('product.save') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="catagory" class="col-sm-2 control-label">หมวดสินค้า :</label>
                        <div class="col-sm-5">
                            <select class="form-control" name="catagory" id="catagory">
                                <option value="">--- กรุณาเลือก ---</option>
                                @foreach ($catagories as $catagory)
                                    <option value="{{ $catagory->category_id }}">{{ $catagory->category_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">ชื่อสินค้า :</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" id="name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="desciption" class="col-sm-2 control-label">รายละเอียดสินค้า :</label>
                        <div class="col-sm-10">
                            <textarea id="editor1" name="editor1" rows="10" cols="80"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="price" class="col-sm-2 control-label">ราคา :</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="price" id="price">
                        </div>
                        <label for="stock" class="col-sm-2 control-label">สต็อคสินค้า :</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="stock" id="stock">
                        </div>
                        <label for="item_sku" class="col-sm-2 control-label">รหัสเรียกสินค้า :</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="item_sku" id="item_sku">
                        </div>
                    </div>
                    <div class="box-footer">
                        <center><button type="submit" class="btn btn-success">บันทึกข้อมูล</button></center>
                    </div>
                </form>
            </div>
        </div>
    </section>

@endsection
@section('scripts')
<script>
$(function () {
    CKEDITOR.replace('editor1');
    $(".textarea").wysihtml5();
});
</script>
@endsection

resources/views/product/index.blade.php
@extends('layouts.layout')

@section('content')
    <section class="content-header">
        <h1>
        ข้อมูลผลิตภัณฑ์
        </h1>
        <ol class="breadcrumb">
            <li class="active"><a href="#"><i class="fa fa-dashboard"></i> ข้อมูลผลิตภัณฑ์</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="box box-primary">
            <div class="box-body">
                <form id="product-search-form" action="{{ route('product.view') }}" method="GET">
                    <div class="col-md-5">
                        <input type="text" class="form-control" name="product" id="product" placeholder="ชื่อสินค้า">
                    </div>
                    <div class="col-md-5">
                        <select class="form-control" name="status" id="status" onchange="product_submit()">
                            <option value="">--- สถานะสินค้า ---</option>
                            <option value="NORMAL">NORMAL</option>
                            <option value="BANNED">BANNED</option>
                            <option value="UNLIST">UNLIST</option>
                        </select>
                    </div>
                    <div class="col-md-2">
                    </div>

                    <div class="col-md-5">
                        <select class="form-control" name="category" id="category" onchange="product_submit()">
                            <option value="">--- หมวดหมู่สินค้า ---</option>
                            @foreach ($catagories as $catagory)
                            <option value="{{ $catagory->category_id }}">{{ $catagory->category_name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-5">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success">
                            <span class="fa fa-search"> ค้นหา
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">รายการสินค้า</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div align="right">
                    {{ $products->links() }}
                </div>
                <table id="tableProduct" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="50px">ชื่อ</th>
                            <th width="20px">รหัสเก็บสินค้า</th>
                            <th>สร้าง</th>
                            <th>ราคาขายปลีก</th>
                            <th>ราคาขาย</th>
                            <th>พร้อมใช้</th>
                            <th>การมองเห็นสินค้า</th>
                            <th>โปรโมชั่นที่ใช้งานอยู่</th>
                            <th>ดำเนินการ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($products as $key => $product)
                            <tr>
                                <td style="width:50px;">{{ $product->name }}</td>
                                <td>{{ $product->item_sku }}</td>
                                <td>{{ ConvertDate1($product->created_at) }}</td>
                                <td>{{ number_format($product->original_price, 2, '.', ',') }}</td>
                                <td>{{ number_format($product->price, 2, '.', ',') }}</td>
                                <td>{{ $product->stock }}</td>
                                <td>{{ $product->has_variation }}</td>
                                <td>&nbsp;</td>
                                <td><center><a href="{{ route('product.show', $product['item_id'])}}" class="btn-sm btn-primary"><i class="fa fa-eye"></i></a></center></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div align="right">
                    {{ $products->appends(Request::except('page'))->links() }}
                </div>
            </div>
            <!-- /.box-body -->
        </div>
    </section>
@endsection

@section('scripts')
<script>
    function product_submit(){
        document.getElementById("product-search-form").submit();
    }
</script>
@endsection

resources/views/product/show.blade.php
@extends('layouts.layout')

@section('content')

    <section class="content-header">
        <h1>
        ข้อมูลสินค้า
        </h1>
        <ol class="breadcrumb">
            <li class="active"><a href="#"><i class="fa fa-dashboard"></i> ข้อมูลสินค้า</a></li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $product->name }}</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-5">
                            @php
                                $getImg = json_decode($product->images);
                            @endphp
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    @foreach ($getImg as $key => $item)
                                        <li data-target="#carousel-example-generic" data-slide-to="{{ $item }}" class="@if($key == 0) active @endif"></li>
                                    @endforeach
                                </ol>
                                <div class="carousel-inner">
                                    @foreach ($getImg as $key => $item)
                                    <div class="item @if($key == 0) active @endif">
                                        <img src="{{ remove_bracketR(remove_bracketL($item)) }}" alt="{{ remove_bracketR(remove_bracketL($item)) }}">
                                    </div>
                                    @endforeach
                                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                      <span class="fa fa-angle-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                      <span class="fa fa-angle-right"></span>
                                    </a>
                                </div>
                            </div>
                    </div>
                    <div class="col-md-7">
                        {{ str_limit(strip_tags($product['description']),2500,' (...)') }}
                    </div>
                </div>
            </div>
        </div>

    </section>

@endsection