routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/forgot', function () {
    return view('auth.passwords.email');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

Route::get('/', 'HomeController@index')->name('home');
//Category//
Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', 'CategoryController@index')->name('view');
});
//Product//
Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', 'ProductController@index')->name('view');
    Route::get('/create', 'ProductController@create')->name('create');
    Route::post('/save', 'ProductController@store')->name('save');
    Route::get('/show/{id}', 'ProductController@show')->name('show');
});
//Order//
Route::group(['prefix' => 'orders', 'as' => 'order.'], function () {
    Route::get('/', 'OrderController@index')->name('view');
    Route::get('/unpaid', 'OrderController@dataUnpaid')->name('unpaid');
    Route::get('/ready', 'OrderController@dataReady')->name('ready');
    Route::get('/complete', 'OrderController@dataComplete')->name('complete');
    Route::get('/show/{id}', 'OrderController@show')->name('show');
    Route::get('/exportorderall/{id}', 'OrderController@exportOrderAll')->name('exportorderall');
    Route::get('/exportdiscountitem/{id}', 'OrderController@exportDiscountItem')->name('exportdiscountitem');
    Route::post('/updatePrint', 'OrderController@updateCountPrint')->name('updatePrint');
    Route::get('/dataOrderAjax', 'OrderController@DataOrderAll')->name('dataAll');
    Route::get('/getbarcode', 'OrderController@barcode')->name('barcode');
    Route::get('/tagsgroup', 'OrderController@barcode')->name('tagsgroup');
    Route::post('/report', 'OrderController@report')->name('report');
});
//User//
Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@index')->name('view');
    Route::get('/create', 'UserController@create')->name('create');
    Route::post('/save', 'UserController@store')->name('save');
    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/update/{id}', 'UserController@update')->name('update');
    Route::post('/disabled', 'UserController@disabled')->name('disabled');
    Route::post('/enabled', 'UserController@enabled')->name('enabled');
    Route::get('/profile/{id}', 'UserController@editProfile')->name('editProfile');
    Route::get('/updateprofile/{id}', 'UserController@updateProfile')->name('updateProfile');
});
//Config//
Route::group(['prefix' => 'configs', 'as' => 'config.'], function () {
    Route::get('/', 'ConfigController@index')->name('view');
    Route::post('/syncdata', 'ConfigController@syncdata')->name('syncdata');
    Route::get('/testdata', 'ConfigController@testdata')->name('testdata');
});
//Shop//
Route::group(['prefix' => 'shops', 'as' => 'shop.'], function () {
    Route::get('/', 'ShopController@index')->name('view');
    Route::get('/edit/{id}', 'ShopController@edit')->name('edit');
});

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo(Role::Class, 'id_role');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::get();
        $users = User::with('role')->paginate(10);
        if(!empty($request->get('name'))){
            $users = User::where('name', 'LIKE', '%'.$request->get('name').'%')->paginate(10);
        }
        if(!empty($request->get('email'))){
            $users = User::where('email', 'LIKE', '%'.$request->get('email').'%')->paginate(10);
        }
        if(!empty($request->get('role'))){
            $users = User::where('id_role', 'LIKE', '%'.$request->get('role').'%')->paginate(10);
        }
        if(!empty($request->get('active'))){
            $users = User::where('active', 'LIKE', '%'.$request->get('active').'%')->paginate(10);
        }

        return view('user.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();

        return view('user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
        ],[
            'name.required' => 'กรุณากรอกชื่อ-นามสกุล/ชื่อร้านค้า',
            'email.required' => 'กรุณากรอกอีเมล์',
            'password.required' => 'กรุณากรอกรหัสผ่าน',
        ]);

        try {
           $user = new User;
           $user->name = $request->input('name');
            $user->email = $request->input('email');
            $user->password = Hash::make($request->input('password'));
            $user->id_role = $request->input('role');
            $user->active = "1";
            $user->portrait = "1";
            $user->save();

            return redirect()->route('user.view')->with('success', 'บันทึกข้อมูลเรียบร้อยแล้ว');
        } catch (\Exception $exception) {
            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::get();
        $user = User::find($id);
        if($user == null){
            return redirect()->route('user.view')->with('error', 'ไม่มีค่า ID นี้');
        }
        return view('user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $user = User::find($id);
            $user->name = $request->input('name');
             $user->email = $request->input('email');
             if(!empty($request->get('password'))) {
                $user->password = Hash::make($request->get('password'));
            } else {
                $user->password = Auth::user()->password;
            }
             $user->id_role = $request->input('role');
             $user->save();

             return redirect()->route('user.view')->with('success', 'แก้ไขข้อมูลเรียบร้อยแล้ว');
         } catch (\Exception $exception) {
             return redirect()->route('user.view')->with('error', $exception->getMessage());
         }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function disabled(Request $request)
    {
        $request->validate([
            'id' => 'required'
        ]);

        try {
            $user = User::find($request->id);
            $user->active = "2";
            $user->save();
            return response()->json(['message'=>"ปิดการใช้งานเรียบร้อยแล้ว.", 'status' => true]);

        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    public function enabled(Request $request)
    {
        $request->validate([
            'id' => 'required'
        ]);

        try {
            $user = User::find($request->id);
            $user->active = "1";
            $user->save();
            return response()->json(['message'=>"ปิดการใช้งานเรียบร้อยแล้ว.", 'status' => true]);

        } catch (Exception $e) {
            die($e->getMessage());
        }
    }
    
    public function editProfile($id)
    {
        $roles = Role::get();
        $user = User::find($id);
        return view('user.profile', compact('user', 'roles'));
    }

    public function updateProfile(Request $request,$id)
    {
        try {
            $user = User::find($id);
            $user->name = $request->input('name');
            $user->email = $request->input('email');
             if(!empty($request->get('password'))) {
                $user->password = Hash::make($request->get('password'));
            } else {
                $user->password = Auth::user()->password;
            }
             $user->id_role = $request->input('role');
             $user->save();

             return redirect()->route('user.editProfile', $user->id)->with('success', 'แก้ไขข้อมูลเรียบร้อยแล้ว');
         } catch (\Exception $exception) {
             return redirect()->route('user.view')->with('error', $exception->getMessage());
         }
    }
}

resources/views/user/create.blade.php
@extends('layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
            สร้างบัญชีผู้ใช้งาน
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-users"></i> บัญชีผู้ใช้งาน</a></li>
                <li class="active">สร้างบัญชีผู้ใช้งาน</li>
            </ol>
        </section>
        <!-- Main content -->
        <section class="content">
            @include('flash_msg')
            <div class="col-md-6">
            <div class="box box-primary">
            <form role="form" action="{{ route('user.save') }}" method="POST">
                    @csrf
                <div class="box-body">
                        <div class="form-group">
                            <label for="name">ชื่อ-นามสกุล/ชื่อร้านค้า</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label for="email">อีเมล์แอดเดรส</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="password">รหัสผ่าน</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label for="role">สิทธิ์ผู้ใช้งาน</label>
                            <select class="form-control" name="role" id="role">
                                <option value="">--- กรุณาเลือก ---</option>
                                @foreach ($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">บันทึกข้อมูล</button>
                </div>
            </form>
            </div>
            </div>
        </section>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.layout')

@section('content')
@include('flash_msg')
        <!-- Content Header (Page header) -->
        <section class="content-header">
                <h1>
                แก้ไขบัญชีผู้ใช้งาน
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-users"></i> บัญชีผู้ใช้งาน</a></li>
                    <li class="active">แก้ไขบัญชีผู้ใช้งาน</li>
                </ol>
            </section>
            <!-- Main content -->
            <section class="content">
                <div class="col-md-6">
                <div class="box box-success">
                <form role="form" action="{{ route('user.update',$user->id) }}" method="POST">
                        @csrf
                    <div class="box-body">
                            <div class="form-group">
                                <label for="name">ชื่อ-นามสกุล/ชื่อร้านค้า</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ $user->name }}">
                            </div>
                            <div class="form-group">
                                <label for="email">อีเมล์แอดเดรส</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ $user->email }}">
                            </div>
                            <div class="form-group">
                                <label for="password">รหัสผ่าน</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                            </div>
                            <div class="form-group">
                                <label for="role">สิทธิ์ผู้ใช้งาน</label>
                                <select class="form-control" name="role" id="role">
                                    <option value="">--- กรุณาเลือก ---</option>
                                    @foreach ($roles as $role)
                                        <option value="{{ $role->id }}" {{($user->id_role == $role->id) ? 'selected' : '' }}>{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">แก้ไขข้อมูล</button>
                    </div>
                </form>
                </div>
                </div>
            </section>

@endsection

resources/views/user/index.blade.php
@extends('layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
            รายการบัญชีผู้ใช้งาน
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-users"></i> บัญชีผู้ใช้งาน</a></li>
                <li class="active">รายการบัญชีผู้ใช้งาน</li>
            </ol>
        </section>
        <!-- Main content -->
        <section class="content">
            @include('flash_msg')
            <div class="box box-primary">
                <div class="box-body">
                    <form id="user-search-form" action="{{ route('user.view') }}" method="GET">
                        <div class="col-md-5">
                            <input type="text" class="form-control" name="name" id="name" placeholder="ชื่อ-นามสกุล">
                        </div>
                        <div class="col-md-5">
                            <input type="text" class="form-control" name="email" id="email" placeholder="อีเมล์">
                        </div>
                        <div class="col-md-2">
                        </div>
                        <div class="col-md-5">
                            <select class="form-control" name="role" id="role" onchange="user_submit()">
                                <option value="">--- สิทธิ์ผู้ใช้งาน ---</option>
                                @foreach ($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-5">
                            <select class="form-control" name="active" id="active" onchange="user_submit()">
                                <option value="">--- สถานะผู้ใช้งาน ---</option>
                                <option value="1">ใช้งาน</option>
                                <option value="2">ไม่ได้ใช้งาน</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-success">
                                <span class="fa fa-search"> ค้นหา
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="box box-default">
                <div class="box-body table-responsive no-padding">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th width="6%">ลำดับที่</th>
                                <th>ชื่อผู้ใช้งาน</th>
                                <th width="30%">ชื่อ-นามสกุล</th>
                                <th>สิทธิ์ผู้ใช้งาน</th>
                                <th>สถานะผู้ใช้งาน</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(count($users) == 0)
                                <tr>
                                    <td colspan="6"><center>--- ไม่มีรายการในตอนนี้ ---</center></td>
                                </tr>
                            @else
                                @foreach ($users as $key => $user)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->role->name }}</td>
                                    @php
                                        $colorActive;
                                        $functionActive;
                                        $iconActive;
                                        if($user->active == 1){
                                            $txtActive = "ใช้งาน";
                                            $colorActive = "danger";
                                            $functionActive = "disabledUser";
                                            $iconActive = "lock";
                                        }elseif($user->active == 2){
                                            $txtActive = "ไม่ได้ใช้งาน";
                                            $colorActive = "warning";
                                            $functionActive = "enabledUser";
                                            $iconActive = "unlock";
                                        }
                                    @endphp
                                    <td>{{ $txtActive }}</td>
                                    <td><a href="{{ route('user.edit',$user->id) }}" class="btn-sm btn-primary"><i class="fa fa-pencil"></i></a><a href="#" onclick="{{ $functionActive }}({{ $user->id }})" class="btn-sm btn-{{ $colorActive }}"><i class="fa fa-{{ $iconActive }}"></i></a></td>
                                </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                    <p align="right">
                        {{ $users->appends(Request::except('page'))->links() }}
                    </p>
                </div>
            </div>
        </section>
@endsection

@section('scripts')
<script>
    function disabledUser(id){
		bootbox.confirm({
        message: "ต้องการปิดผู้ใช้งานนี้ ?",
        buttons: {
            confirm: {
                label: 'ตกลง',
                className: 'btn-success'
            },
            cancel: {
                label: 'ยกเลิก',
                className: 'btn-danger'
            }
        },
        callback: function(result) {
			if(result) {
                $.ajax({
                    type: "POST",
                    url: "{{ route('user.disabled') }}",
                    dataType: 'JSON',
                    data: { id : id,
                      _token: "{{ csrf_token() }}",
                    },
                    success: function(data){
                        if(data.status == true){
                            alert('ปิดการใช้งานเรียบร้อยแล้ว')
                            window.location.reload();
                        }
                    }
                });
			}
        }
		});
    }
    function enabledUser(id){
        bootbox.confirm({
        message: "ต้องการเปิดผู้ใช้งานนี้ ?",
        buttons: {
            confirm: {
                label: 'ตกลง',
                className: 'btn-success'
            },
            cancel: {
                label: 'ยกเลิก',
                className: 'btn-danger'
            }
        },
        callback : function(result){
            if(result){
                $.ajax({
                    type: "POST",
                    url: "{{ route('user.enabled') }}",
                    dataType: 'JSON',
                    data: { id : id,
                        _token: "{{ csrf_token() }}",
                    },
                    success: function(data){
                        if(data.status == true){
                            alert('เปิดการใช้งานเรียบร้อยแล้ว')
                            window.location.reload();
                        }
                    }
                })
            }
        }
        });
    }

    function user_submit(){
        document.getElementById("user-search-form").submit();
    }
</script>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.layout')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
            ตั้งค่าบัญชี
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-users"></i> บัญชีผู้ใช้งาน</a></li>
                <li class="active">ตั้งค่าบัญชี</li>
            </ol>
        </section>
        <section class="content">
            @include('flash_msg')
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                                <img class="profile-user-img img-responsive img-circle" src="{{ asset('img/no_img.png') }}" alt="User profile picture">
                                <h3 class="profile-username text-center">{{ $user->name }}</h3>
                                <p class="text-muted text-center">{{ $user->role->name }}</p>
                                <form class="form-horizontal" action="{{ route('user.updateProfile', $user->id) }}" method="get">
                                    <div class="form-group">
                                        <label for="inputName" class="col-sm-2 control-label">ชื่อ-นามสกุล/ชื่อร้านค้า</label>

                                        <div class="col-sm-10">
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ $user->name }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="inputEmail" class="col-sm-2 control-label">อีเมล์แอดเดรส</label>

                                        <div class="col-sm-10">
                                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ $user->email }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class="col-sm-2 control-label">รหัสผ่าน</label>
                                        <div class="col-sm-10">
                                            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="role" class="col-sm-2 control-label">สิทธิ์ผู้ใช้งาน</label>
                                        <div class="col-sm-10">
                                        <select class="form-control" name="role" id="role" disabled>
                                            <option value="">--- กรุณาเลือก ---</option>
                                            @foreach ($roles as $role)
                                                <option value="{{ $role->id }}" {{($user->id_role == $role->id) ? 'selected' : '' }}>{{ $role->name }}</option>
                                            @endforeach
                                        </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="">
                                            <center><button type="submit" class="btn btn-danger">แก้ไขข้อมูล</button></center>
                                        </div>
                                    </div>
                                    <input type="hidden" name="role" value="{{ $user->id_role }}">
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>


@endsection