routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});
Route::get('/forgot', function () {
    return view('auth.passwords.email');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

Route::get('/', 'HomeController@index')->name('home');
//Category//
Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', 'CategoryController@index')->name('view');
});
//Product//
Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', 'ProductController@index')->name('view');
    Route::get('/create', 'ProductController@create')->name('create');
    Route::post('/save', 'ProductController@store')->name('save');
    Route::get('/show/{id}', 'ProductController@show')->name('show');
});
//Order//
Route::group(['prefix' => 'orders', 'as' => 'order.'], function () {
    Route::get('/', 'OrderController@index')->name('view');
    Route::get('/unpaid', 'OrderController@dataUnpaid')->name('unpaid');
    Route::get('/ready', 'OrderController@dataReady')->name('ready');
    Route::get('/complete', 'OrderController@dataComplete')->name('complete');
    Route::get('/show/{id}', 'OrderController@show')->name('show');
    Route::get('/exportorderall/{id}', 'OrderController@exportOrderAll')->name('exportorderall');
    Route::get('/exportdiscountitem/{id}', 'OrderController@exportDiscountItem')->name('exportdiscountitem');
    Route::post('/updatePrint', 'OrderController@updateCountPrint')->name('updatePrint');
    Route::get('/dataOrderAjax', 'OrderController@DataOrderAll')->name('dataAll');
    Route::get('/getbarcode', 'OrderController@barcode')->name('barcode');
    Route::get('/tagsgroup', 'OrderController@barcode')->name('tagsgroup');
    Route::post('/report', 'OrderController@report')->name('report');
});
//User//
Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@index')->name('view');
    Route::get('/create', 'UserController@create')->name('create');
    Route::post('/save', 'UserController@store')->name('save');
    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/update/{id}', 'UserController@update')->name('update');
    Route::post('/disabled', 'UserController@disabled')->name('disabled');
    Route::post('/enabled', 'UserController@enabled')->name('enabled');
    Route::get('/profile/{id}', 'UserController@editProfile')->name('editProfile');
    Route::get('/updateprofile/{id}', 'UserController@updateProfile')->name('updateProfile');
});
//Config//
Route::group(['prefix' => 'configs', 'as' => 'config.'], function () {
    Route::get('/', 'ConfigController@index')->name('view');
    Route::post('/syncdata', 'ConfigController@syncdata')->name('syncdata');
    Route::get('/testdata', 'ConfigController@testdata')->name('testdata');
});
//Shop//
Route::group(['prefix' => 'shops', 'as' => 'shop.'], function () {
    Route::get('/', 'ShopController@index')->name('view');
    Route::get('/edit/{id}', 'ShopController@edit')->name('edit');
});

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=K2D" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/inc-menu.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>M</b>P</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Market</b>Place</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              @php
                  $countOrder = App\Order::count();
              @endphp
                    <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                      <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">{{ $countOrder }}</span>
                    </a>
                    </li>
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                      <!-- Menu Toggle Button -->
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset('img/no_img.png') }}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                      </a>
                      <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                          <img src="{{ asset('img/no_img.png') }}" class="img-circle" alt="User Image">

                          <p>
                            {{ Auth::user()->name }}
                            <small>{{ Auth::user()->role->name }}</small>
                          </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                          <div class="pull-left">
                            <a href="{{ route('user.editProfile', Auth::user()->id) }}" class="btn btn-default btn-flat">ตั้งค่าบัญชี</a>
                          </div>
                          <div class="pull-right">
                            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">ออกจากระบบ</a>
                          </div>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                      </ul>
                </li>
            </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <ul class="sidebar-menu">
                @if(Auth::user()->id_role == 1 || Auth::user()->id_role == 2)
                <li class="treeview">
                    <a href="{{ route('home') }}"><i class="fa fa-dashboard"></i>&nbsp;ข้อมูลรวม</a>
                </li>
                <li class="treeview {{ Request::is( 'products', 'products/create', 'categories') ? 'active' : '' }}">
                <a href="#"><i class="fa fa-archive"></i>&nbsp;ผลิตภัณฑ์
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ Request::is( 'products') ? 'active' : '' }}"><a href="{{ route('product.view') }}"><i class="fa fa-circle-o"></i> รายการสินค้า</a></li>
                    <li class="{{ Request::is( 'products/create') ? 'active' : '' }}"><a href="{{ route('product.create') }}"><i class="fa fa-circle-o"></i> เพิ่มสินค้า</a></li>
                    <li class="{{ Request::is( 'categories') ? 'active' : '' }}"><a href="{{ route('category.view') }}"><i class="fa fa-circle-o"></i> หมวดสินค้า</a></li>
                </ul>
                </li>
                <li class="treeview {{ Request::is( 'orders', 'orders/unpaid', 'orders/ready', 'orders/complete') ? 'active' : '' }}">
                    <a href="#"><i class="fa fa-cart-plus"></i>&nbsp;คำสั่งซื้อ
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{{ Request::is( 'orders', 'orders/unpaid', 'orders/ready', 'orders/complete') ? 'active' : '' }}"><a href="{{ route('order.view') }}"><i class="fa fa-circle-o"></i> รายการคำสั่งซื้อ</a></li>
                    </ul>
                </li>
                @endif
                @if(Auth::user()->id_role == 1)
                <li class="treeview {{ Request::is( 'users', 'users/create') ? 'active' : '' }}">
                    <a href="#"><i class="fa fa-users"></i>&nbsp;บัญชีผู้ใช้งาน
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{{ Request::is( 'users') ? 'active' : '' }}"><a href="{{ route('user.view') }}"><i class="fa fa-circle-o"></i> รายการผู้ใช้งาน</a></li>
                        <li class="{{ Request::is( 'users/create') ? 'active' : '' }}"><a href="{{ route('user.create') }}"><i class="fa fa-circle-o"></i> สร้างผู้ใช้งาน</a></li>
                    </ul>
                </li>
                <li class="treeview {{ Request::is( 'shops') ? 'active' : '' }}">
                    <a href="#"><i class="fa fa-gear"></i>&nbsp;ตั้งค่าระบบ
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{{ Request::is( 'shops') ? 'active' : '' }}"><a href="{{ route('shop.view') }}"><i class="fa fa-circle-o"></i> ตั้งค่าร้าน</a></li>
                    </ul>
                </li>
                @endif
          </ul>
        </section>
        <!-- /.sidebar -->
        <center><button type="button" class="btn bg-orange margin" onclick="shinkData('52591873','840997','1f30a88d84b5e4d2309307e799ff20079a4b30163c5e3d652203f0386eeb266e');"><i class="fa fa-refresh"></i>&nbsp;อัพเดตข้อมูลร้าน</button></center>
    </aside>

resources/views/layouts/inc-scripts.blade.php
<!-- jQuery 2.2.3 -->
<script src="{{ asset('js/jquery-2.2.3.min.js')}}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ asset('js/bootstrap.js') }}"></script>
<!-- iCheck -->
<script src="{{ asset('js/icheck.js') }}"></script>
<!-- AdminLTE -->
<script src="{{ asset('js/app.min.js') }}"></script>
<!-- BootBox -->
<script src="{{ asset('js/bootbox.min.js') }}"></script>
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>

<script>
  $(function () {
//     $('input').iCheck({
//       checkboxClass: 'icheckbox_square-blue',
//       radioClass: 'iradio_square-blue',
//       increaseArea: '20%' // optional
//     });
  });
  function shinkData(shopId,partnerId,secretId){
    bootbox.confirm({
        message: "ต้องการอัพเดตข้อมูลร้าน?",
        buttons: {
            confirm: {
                label: 'ใช่',
                className: 'btn-success'
            },
            cancel: {
                label: 'ไม่',
                className: 'btn-danger'
            }
        },
        callback: function (result) {
            if(result) {
                $.ajax({
                        type: "POST",
                        url: "{{ route('config.syncdata') }}",
                        dataType: 'JSON',
                        data: {
                            _token: "{{ csrf_token() }}",
                            shopid : shopId,
                            partner_id : partnerId,
                            secret : secretId,
                        },
                        beforeSend: function(){
                            bootbox.dialog({ 
                                message: '<div class="text-center"><i class="fa fa-spin fa-spinner"></i> <br><h3>กำลังอัพเดตข้อมูลร้านของคุณ กรุณารอสักครู่...</h3></div>',
                                closeButton: false 
                            });
                        },
                        success: function(data){
                            if(data.status == true){
                                bootbox.alert({
                                    message: "อัพเดตข้อมูลร้านเรียบร้อยแล้ว",
                                    callback: function () {
                                        window.location.reload();
                                    }
                                })
                            }
                        },
                        error: function(jqXHR, exception){
                            var msg = '';
                            if (jqXHR.status === 0) {
                                msg = 'Not connect.\n Verify Network.';
                            } else if (jqXHR.status == 404) {
                                msg = 'Requested page not found. [404]';
                            } else if (jqXHR.status == 500) {
                                msg = 'Error 500.';
                            } else if (exception === 'parsererror') {
                                msg = 'Requested JSON parse failed.';
                            } else if (exception === 'timeout') {
                                msg = 'Time out error.';
                            } else if (exception === 'abort') {
                                msg = 'Ajax request aborted.';
                            } else {
                                msg = 'Uncaught Error.\n' + jqXHR.responseText;
                            }
                            alert(msg);
                        }
                });
            }
        }
    });
    }
</script>

resources/views/layouts/inc-stylesheets.blade.php
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('css/AdminLTE.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('css/skins/_all-skins.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('css/blue.css') }}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style>
  #loading {
   width: 100%;
   height: 100%;
   top: 0px;
   left: 0px;
   position: fixed;
   display: block;
   opacity: 0.9;
   background-color: #fff;
   z-index: 99;
   text-align: center;
}
#loading-content {
  position: absolute;
  top: 40%;
  left: 32%;
  text-align: center;
  z-index: 100;
}
.hide{
  display: none;
}
//Font//
@font-face {
            font-family: 'THSarabunNew';
            font-style: normal;
            font-weight: normal;
            src: url("{{ asset('fonts/THSarabunNew.ttf') }}") format('truetype');
        }
        @font-face {
            font-family: 'THSarabunNew';
            font-style: normal;
            font-weight: bold;
            src: url("{{ asset('fonts/THSarabunNew Bold.ttf') }}") format('truetype');
        }
        @font-face {
            font-family: 'THSarabunNew';
            font-style: italic;
            font-weight: normal;
            src: url("{{ asset('fonts/THSarabunNew Italic.ttf') }}") format('truetype');
        }
        @font-face {
            font-family: 'THSarabunNew';
            font-style: italic;
            font-weight: bold;
            src: url("{{ asset('fonts/THSarabunNew BoldItalic.ttf') }}") format('truetype');
        }
  </style>

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="token" content="{{ csrf_token() }}">
    <title>ระบบจัดการคำสั่งซื้อสินค้า MarketPlaces</title>
    @include('layouts.inc-stylesheets')
    @yield('stylesheets')
</head>
<body class="hold-transition skin-green sidebar-mini">
<div class="wrapper">
    @include('layouts.inc-menu')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        @yield('content')
  </div>
  @include('layouts.inc-scripts')
  @yield('scripts')
</div>
</body>
</html>